name: 💡 Feature request
description: Suggest an improvement or new feature
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion!
        Please describe the idea and how it would help you.

  - type: textarea
    id: idea
    attributes:
      label: Feature idea
      description: What would you like to see added or improved?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: What pain point does this address?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Usage context
      description: How would you use this in real life?
    validations:
      required: false
